### ISSUE TITLE
error when running on python3.5

### ISSUE THREAD

**Issue by vvanamu** [vladikk/JSON2CSV#1]
Hi there,

I am getting the following error message when I run the script on python3.5
Had no issues and worked flawlessly on python2.6
Please let me know how I can make this script compatible with python3

Traceback (most recent call last):
  File "json2csv.py", line 64, in <module>
    json_to_csv("responses.json", "responses.csv")
  File "json2csv.py", line 12, in json_to_csv
    dicts = json_to_dicts(json)
  File "json2csv.py", line 26, in json_to_dicts
    return [dict(to_keyvalue_pairs(obj)) for obj in objects]
  File "json2csv.py", line 26, in <listcomp>
    return [dict(to_keyvalue_pairs(obj)) for obj in objects]
  File "json2csv.py", line 36, in to_keyvalue_pairs
    result = [to_keyvalue_pairs(source[key], ancestors + [key]) for key in source.keys()]
  File "json2csv.py", line 36, in <listcomp>
    result = [to_keyvalue_pairs(source[key], ancestors + [key]) for key in source.keys()]
  File "json2csv.py", line 39, in to_keyvalue_pairs
    result = [to_keyvalue_pairs(item, ancestors + [str(index)]) for (index, item) in enumerate(source)]
  File "json2csv.py", line 39, in <listcomp>
    result = [to_keyvalue_pairs(item, ancestors + [str(index)]) for (index, item) in enumerate(source)]
  File "json2csv.py", line 39, in to_keyvalue_pairs
    result = [to_keyvalue_pairs(item, ancestors + [str(index)]) for (index, item) in enumerate(source)]
  File "json2csv.py", line 39, in <listcomp>
    result = [to_keyvalue_pairs(item, ancestors + [str(index)]) for (index, item) in enumerate(source)]
  File "json2csv.py", line 39, in to_keyvalue_pairs
    result = [to_keyvalue_pairs(item, ancestors + [str(index)]) for (index, item) in enumerate(source)]
  File "json2csv.py", line 39, in <listcomp>
    result = [to_keyvalue_pairs(item, ancestors + [str(index)]) for (index, item) in enumerate(source)]
  File "json2csv.py", line 39, in to_keyvalue_pairs
    result = [to_keyvalue_pairs(item, ancestors + [str(index)]) for (index, item) in enumerate(source)]
  File "json2csv.py", line 39, in <listcomp>
    result = [to_keyvalue_pairs(item, ancestors + [str(index)]) for (index, item) in enumerate(source)]
  File "json2csv.py", line 39, in to_keyvalue_pairs
    result = [to_keyvalue_pairs(item, ancestors + [str(index)]) for (index, item) in enumerate(source)]
  File "json2csv.py", line 39, in <listcomp>
    result = [to_keyvalue_pairs(item, ancestors + [str(index)]) for (index, item) in enumerate(source)]
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by vladikk** [comment]
Ported to python3
